/**********************************************************************

     Name:     LTE RRC Layer

     Type:     Header file

     Desc:     Defines required by RRC

     File:     nhu_3gasn.h

     Sid:      nhu_3gasn.h@@/main/1 - Fri Dec 11 18:45:13 2009

     Prg:      chebli

**********************************************************************/
#ifndef __NHU3GASNH__
#define __NHU3HASNH__ 

#define NHUCHKUNPKPTR(func, val, ptr, mBuf) {\
   S16 ret;\
   if ((ret = func(val, mBuf, ptr)) != ROK)\
      RETVALUE(ret);\
}
#define Nhuid_Invalid 0xffffffff
#define NhuhiPDSCHidentities 64
#define NhuhiPUSCHidentities 64
#define NhuhiRM 256
#define NhumaxAC 16
#define NhumaxAdditionalMeas 4
#define NhumaxASC 8
#define NhumaxASCmap 7
#define NhumaxASCpersist 6
#define NhumaxCCTrCH 8
#define NhumaxCellMeas 32
#define NhumaxCellMeasOnSecULFreq 32
#define NhumaxCellMeas_1 31
#define NhumaxCellMeasOnSecULFreq_1 31
#define NhumaxCNdomains 4
#define NhumaxCmnHRNTI 4
#define NhumaxCmnQueueID 2
#define NhumaxCPCHsets 16
#define NhumaxDedicatedCSGFreq 4
#define NhumaxDPCH_DLchan 8
#define NhumaxDPDCH_UL 6
#define NhumaxDRACclasses 8
#define NhumaxE_DCHMACdFlow 8
#define NhumaxE_DCHMACdFlow_1 7
#define NhumaxEUTRACellPerFreq 16
#define NhumaxEUTRATgtFreqs 8
#define NhumaxEDCHRL 4
#define NhumaxEDCHRL_1 3
#define NhumaxEDCHs 32
#define NhumaxEDCHTxPattern_TDD128 4
#define NhumaxEDCHTxPattern_TDD128_1 3
#define NhumaxERNTIgroup 32
#define NhumaxERNTIperGroup 2
#define NhumaxERUCCH 256
#define NhumaxFACHPCH 8
#define NhumaxFreq 8
#define NhumaxFreqBandsEUTRA 16
#define NhumaxFreqBandsFDD 8
#define NhumaxFreqBandsFDD2 22
#define NhumaxFreqBandsFDD_ext 15
#define NhumaxFreqBandsFDD_ext2 64
#define NhumaxFreqBandsIndicatorSupport 2
#define NhumaxFreqBandsTDD 4
#define NhumaxFreqBandsTDD_ext 16
#define NhumaxFreqBandsGSM 16
#define NhumaxFreqMeasWithoutCM 2
#define NhumaxGANSS 8
#define NhumaxGANSS_1 7
#define NhumaxGANSSSat 64
#define NhumaxGANSSSat_1 63
#define Nhu3gmaxGERAN_SI 8
#define NhumaxGSMTgtCells 32
#define NhumaxHNBNameSize 48
#define NhumaxHProcesses 8
#define NhumaxHS_SCCHLessTrBlk 4
#define NhumaxHSDSCHTBIdx 64
#define NhumaxHSDSCHTBIdx_tdd384 512
#define NhumaxHSSCCHs 4
#define NhumaxHSSCCHs_1 3
#define NhumaxHSSICH_TDD128 4
#define NhumaxHSSICH_TDD128_1 3
#define NhumaxInterSysMsgs 4
#define NhumaxLoCHperRLC 2
#define NhumaxLoggedMeasReport 128
#define NhumaxMAC_d_PDUsizes 8
#define NhumaxMBMS_CmnCCTrCh 32
#define NhumaxMBMS_CmnPhyCh 32
#define NhumaxMBMS_CmnRB 32
#define NhumaxMBMS_CmnTrCh 32
#define NhumaxMBMS_Freq 4
#define NhumaxMBMS_L1CP 4
#define NhumaxMBMSservCount 8
#define NhumaxMBMSservModif 32
#define NhumaxMBMSservSched 16
#define NhumaxMBMSservSelect 8
#define NhumaxMBMSservUnmodif 64
#define NhumaxMBMSTransmis 4
#define NhumaxMBSFNClusters 16
#define NhumaxMeasCSGRange 4
#define NhumaxMeasEvent 8
#define NhumaxMeasEventOnSecULFreq 8
#define NhumaxMeasIntervals 3
#define NhumaxMeasOccasionPattern 5
#define NhumaxMeasOccasionPattern_1 4
#define NhumaxMeasParEvent 2
#define NhumaxNonContiguousMultiCellCombinations 3
#define NhumaxNumCDMA2000Freqs 8
#define NhumaxNumE_AGCH 4
#define NhumaxNumE_HICH 4
#define NhumaxNumEUTRAFreqs 8
#define NhumaxNumGSMCellGroup 16
#define NhumaxNumGSMFreqRanges 32
#define NhumaxNumFDDFreqs 8
#define NhumaxNumANRLoggedItems 4
#define NhumaxnumLoggedMeas 8
#define NhumaxNumTDDFreqs 8
#define NhumaxNoOfMeas 16
#define NhumaxOtherRAT 15
#define NhumaxOtherRAT_16 16
#define NhumaxPage1 8
#define NhumaxPCPCH_APsig 16
#define NhumaxPCPCH_APsubCh 12
#define NhumaxPCPCH_CDsig 16
#define NhumaxPCPCH_CDsubCh 12
#define NhumaxPCPCH_SF 7
#define NhumaxPCPCHs 64
#define NhumaxPDCPAlgoTyp 8
#define NhumaxPDSCH 8
#define NhumaxPDSCH_TFCIgroups 256
#define NhumaxPRACH 16
#define NhumaxPRACH_FPACH 8
#define NhumaxPredefConfig 16
#define NhumaxPrio 8
#define NhumaxPrio_1 7
#define NhumaxPUSCH 8
#define NhumaxQueueIDs 8
#define NhumaxRABsetup 16
#define NhumaxRAT 16
#define NhumaxRB 32
#define NhumaxRBallRABs 27
#define NhumaxRBMuxOptions 8
#define NhumaxRBperRAB 8
#define NhumaxRBperTrCh 16
#define NhumaxReportedEUTRACellPerFreq 4
#define NhumaxReportedEUTRAFreqs 4
#define NhumaxReportedGSMCells 8
#define NhumaxRL 8
#define NhumaxRL_1 7
#define NhumaxRLCPDUsizePerLogChan 32
#define NhumaxRFC3095_CID 16384
#define NhumaxROHC_PacketSizes_r4 16
#define NhumaxROHC_Profile_r4 8
#define NhumaxRxPatternForHSDSCH_TDD128 4
#define NhumaxRxPatternForHSDSCH_TDD128_1 3
#define NhumaxSat 16
#define NhumaxSatClockModels 4
#define NhumaxSCCPCH 16
#define NhumaxSgnTyp 8
#define NhumaxSIB 32
#define NhumaxSIB_FACH 8
#define NhumaxSIBperMsg 16
#define NhumaxSIrequest 4
#define NhumaxSRBsetup 8
#define NhumaxSysCap 16
#define NhumaxTDD128Carrier 6
#define NhumaxTDD128Carrier_1 5
#define NhumaxTbsForHSDSCH_TDD128 4
#define NhumaxTbsForHSDSCH_TDD128_1 3
#define NhumaxTF 32
#define NhumaxTF_CPCH 16
#define NhumaxTFC 1024
#define NhumaxTFCsub 1024
#define NhumaxTFCI_2_Combs 512
#define NhumaxTGPS 6
#define NhumaxTrCH 32
#define NhumaxTrCHpreconf 32
#define NhumaxTS 14
#define NhumaxTS_1 13
#define NhumaxTS_2 12
#define NhumaxTS_LCR 6
#define NhumaxTS_LCR_1 5
#define NhumaxURA 8
#define NhumaxURNTI_Group 8

#define CN_TYP_GSM_MAP 0
#define CN_TYP_ANSI_41 1

#define ROUTINGBASIS_LOCALPTMSI 0
#define ROUTINGBASIS_TMSIOFSAMEPLMN 1
#define ROUTINGBASIS_TMSIOFDIFFERENTPLMN 2
#define ROUTINGBASIS_IMSIRESPONSETOPAGING 3
#define ROUTINGBASIS_IMSICAUSEUEINITIATEDEVENT 4
#define ROUTINGBASIS_IMEI 5
#define ROUTINGBASIS_SPARE2 6
#define ROUTINGBASIS_SPARE1 7

#define CN_TYP_GSM_MAP_IDNNS 0
#define CN_TYP_ANSI_41_IDNNS 1
#define VERSION_RELEASE99 0
#define VERSION_LATER 1

#define LOCREGISTRATIONPARAMS_NORESTRN 0
#define LOCREGISTRATIONPARAMS_RESTRICTION 1

#define PAGPERMISSIONWITHACCESSCNTRLFORSHAREDNW_PAGINGPERMISSIONWITHACCESSCNTRLLST 0
#define PAGPERMISSIONWITHACCESSCNTRLFORSHAREDNW_PAGINGPERMISSIONWITHACCESSCNTRLFORALL 1

#define PLMN_TYP_GSM_MAP 0
#define PLMN_TYP_ANSI_41 1
#define PLMN_TYP_GSM_MAP_AND_ANSI_41 2
#define PLMN_TYP_SPARE 3

#define RAB_IDENTITY_GSM_MAP_RAB_IDENTITY 0
#define RAB_IDENTITY_ANSI_41_RAB_IDENTITY 1

#define CELLBARRED_BARRED 0
#define CELLBARRED_NOTBARRED 1

#define T_CRMAX_NOTUSED 0
#define T_CRMAX_T30 1
#define T_CRMAX_T60 2
#define T_CRMAX_T120 3
#define T_CRMAX_T180 4
#define T_CRMAX_T240 5

#define CELLSELECTQUALITYMEASURE_CPICH_EC_N0_0 0
#define CELLSELECTQUALITYMEASURE_CPICH_RSCP_1 1
#define MODESPECIFICINFO_FDD 0
#define MODESPECIFICINFO_TDD 1

#define MODESPECIFICINFO_FDD_1 1
#define MODESPECIFICINFO_TDD_0 

#define DOMAINSPECIFICACCESSRESTRN_V670EXT_NORESTRN 0
#define DOMAINSPECIFICACCESSRESTRN_V670EXT_RESTRICTION 1

#define DOMAINSPECIFICACCESSRESTRNFORSHAREDNW_V670EXT_DOMAINSPECIFICACCESSRESTICTIONLST 0
#define DOMAINSPECIFICACCESSRESTRNFORSHAREDNW_V670EXT_DOMAINSPECIFICACCESSRESTICTIONPARAMSFORALL 1

#define FOLLOWINGARFCNS_EXPLICITLSTOFARFCNS 0
#define FOLLOWINGARFCNS_EQUALLYSPACEDARFCNS 1
#define FOLLOWINGARFCNS_VARIABLEBITMAPOFARFCNS 2
#define FOLLOWINGARFCNS_CONTINUOUSRANGEOFARFCNS 3

#define RADIOACCESSTECHNOLOGY_UTRAFDD 0
#define RADIOACCESSTECHNOLOGY_UTRATDD 1
#define RADIOACCESSTECHNOLOGY_EUTRA 2
#define RADIOACCESSTECHNOLOGY_GSM 3

#define ACTION_CLEARDEDICATEDPRIORITIES 0
#define ACTION_CONFIGUREDEDICATEDPRIORITIES 1

#define CIPHERINGMODECMD_STARTRESTART 0
#define CIPHERINGMODECMD_DUMMY 1

#define CN_PAGEDUE_IDENTITY_IMSI_GSM_MAP 0
#define CN_PAGEDUE_IDENTITY_TMSI_GSM_MAP 1
#define CN_PAGEDUE_IDENTITY_P_TMSI_GSM_MAP 2
#define CN_PAGEDUE_IDENTITY_IMSI_DS_41 3
#define CN_PAGEDUE_IDENTITY_TMSI_DS_41 4
#define CN_PAGEDUE_IDENTITY_SPARE3 5
#define CN_PAGEDUE_IDENTITY_SPARE2 6
#define CN_PAGEDUE_IDENTITY_SPARE1 7

#define POWERCNTRLALGORITHM_ALGORITHM1 0
#define POWERCNTRLALGORITHM_ALGORITHM2 1

#define SIMULTANEOUSSCCPCH_DPCH_RECEPTION_NOTSUPP 0
#define SIMULTANEOUSSCCPCH_DPCH_RECEPTION_SUPPORTED 1

#define TDD768_HSPDSCH_SUPPORTED 0
#define TDD768_HSPDSCH_UNSUPPORTED 1

#define TURBOSUPPORT_NOTSUPP 0
#define TURBOSUPPORT_SUPPORTED 1

#define DIAGNOSTICSTYP_TYPE1 0
#define DIAGNOSTICSTYP_SPARE 1

#define FAILCAUSEWITHPROTERR_CONFIGURATIONUNSUPPORTED 0
#define FAILCAUSEWITHPROTERR_PHYSICALCHANNELFAIL 1
#define FAILCAUSEWITHPROTERR_INCOMPATIBLESIMULTANEOUSRECFGN 2
#define FAILCAUSEWITHPROTERR_COMPRESSEDMODERUNTIMEERR 3
#define FAILCAUSEWITHPROTERR_PROTOCOLERR 4
#define FAILCAUSEWITHPROTERR_CELLUPDOCCURRED 5
#define FAILCAUSEWITHPROTERR_INVALIDCFG 6
#define FAILCAUSEWITHPROTERR_CONFIGURATIONINCOMPLETE 7
#define FAILCAUSEWITHPROTERR_UNSUPPORTEDMEASUREMENT 8
#define FAILCAUSEWITHPROTERR_MBMSSESSIONALREADYRECEIVEDCORRECTLY 9
#define FAILCAUSEWITHPROTERR_LOWERPRIORITYMBMSSERVICE 10
#define FAILCAUSEWITHPROTERR_SPARE5 11
#define FAILCAUSEWITHPROTERR_SPARE4 12
#define FAILCAUSEWITHPROTERR_SPARE3 13
#define FAILCAUSEWITHPROTERR_SPARE2 14
#define FAILCAUSEWITHPROTERR_SPARE1 15

#define FREQUENCYBANDSINDICATORFDD_FREQUENCYBANDSINDICATOR1 0
#define FREQUENCYBANDSINDICATORFDD_FREQUENCYBANDSINDICATOR2 1
#define FREQUENCYBANDSINDICATORFDD_FREQUENCYBANDSINDICATOR3 2


#define U_RNTI_GROUP_ALL 0
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B1 1
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B2 2
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B3 3
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B4 4
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B5 5
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B6 6
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B7 7
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B8 8
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B9 9
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B10 10
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B11 11
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B12 12
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B13 13
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B14 14
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B15 15
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B16 16
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B17 17
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B18 18
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B19 19
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B20 20
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B21 21
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B22 22
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B23 23
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B24 24
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B25 25
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B26 26
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B27 27
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B28 28
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B29 29
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B30 30
#define U_RNTI_GROUP_U_RNTI_BITMASKIDX_B31 31

#define SUPPORTFORRFC2507_NOTSUPP 0
#define SUPPORTFORRFC2507_SUPPORTED 1

#define SUPPORTFORRFC3095_NOTSUPP 0
#define SUPPORTFORRFC3095_SUPPORTED 1

#define TDD384_EDCH_SUPPORTED 0
#define TDD384_EDCH_UNSUPPORTED 1

#define TDD384_EDCH_SUPPORTED 0
#define TDD384_EDCH_UNSUPPORTED 1

#define TDD128_EDCH_SUPPORTED 0
#define TDD128_EDCH_UNSUPPORTED 1

#define FDD_HSPDSCH_SUPPORTED 0
#define FDD_HSPDSCH_UNSUPPORTED 1
#define TDD384_HSPDSCH_SUPPORTED 0
#define TDD384_HSPDSCH_UNSUPPORTED 1
#define TDD128_HSPDSCH_SUPPORTED 0
#define TDD128_HSPDSCH_UNSUPPORTED 1

#define PROTERRINDICATORWITHMOREINFO_NOERR 0
#define PROTERRINDICATORWITHMOREINFO_ERROROCCURRED 1

#define TYPE1_ASN1_VIOLATIONORENCODINGERR 0
#define TYPE1_MESSAGETYPNONEXISTENT 1
#define TYPE1_MESSAGENOTCOMPATIBLEWITHRECEIVERSTATE 2
#define TYPE1_IE_VALUENOTCOMPREHENDED 3
#define TYPE1_CONDITIONALINFOELEMENTERR 4
#define TYPE1_MESSAGEEXTNNOTCOMPREHENDED 5
#define TYPE1_SPARE1 6
#define TYPE1_SPARE2 7
#define DIAGNOSTICSTYP_TYPE1 0
#define DIAGNOSTICSTYP_SPARE 1

#define REDIRECTIONINFO_FREQUENCYINFO 0
#define REDIRECTIONINFO_INTERRATINFO 1

#define REDIRECTIONINFO_R6_FREQUENCYINFO 0
#define REDIRECTIONINFO_R6_INTERRATINFO 1

#define INTERRATINFO_V860EXT_GSM 0
#define INTERRATINFO_V860EXT_EUTRA 1

#define REDIRECTIONINFO_V860EXT_FREQUENCYINFO 0
#define REDIRECTIONINFO_V860EXT_INTERRATINFO 1


#define FDD_EDCH_SUPPORTED 0
#define FDD_EDCH_UNSUPPORTED 1

#define FDD_NOTSUPP 0
#define FDD_SUPPORTED 1
#define TDD384_RF_CAP_NOTSUPP 0
#define TDD384_RF_CAP_SUPPORTED 1
#define TDD128_RF_CAP_NOTSUPP 0
#define TDD128_RF_CAP_SUPPORTED 1

#define TDD768_RF_CAP_NOTSUPP 0
#define TDD768_RF_CAP_SUPPORTED 1

#define ALGORITHMSPECIFICINFO_RFC2507_INFO 0

#define ALGORITHMSPECIFICINFO_R4_RFC2507_INFO 0
#define ALGORITHMSPECIFICINFO_R4_RFC3095_INFO 1

#define OCTETMODERLC_SIZEINFOTYP1_SIZETYP1 0
#define OCTETMODERLC_SIZEINFOTYP1_SIZETYP2 1
#define OCTETMODERLC_SIZEINFOTYP1_SIZETYP3 2

#define DL_RLC_PDU_SIZE_FIXEDSIZE 0
#define DL_RLC_PDU_SIZE_FLEXIBLESIZE 1

#define DL_TPORTCHANNELTYP_DCH 0
#define DL_TPORTCHANNELTYP_FACH 1
#define DL_TPORTCHANNELTYP_DSCH 2
#define DL_TPORTCHANNELTYP_DCH_AND_DSCH 3

#define DL_TPORTCHANNELTYP_R5_DCH 0
#define DL_TPORTCHANNELTYP_R5_FACH 1
#define DL_TPORTCHANNELTYP_R5_DSCH 2
#define DL_TPORTCHANNELTYP_R5_DCH_AND_DSCH 3
#define DL_TPORTCHANNELTYP_R5_HSDSCH 4
#define DL_TPORTCHANNELTYP_R5_DCH_AND_HSDSCH 5

#define HSDSCH_MAC_HS 0
#define HSDSCH_MAC_EHS 1
#define DCH_AND_HSDSCH_MAC_HS 0
#define DCH_AND_HSDSCH_MAC_EHS 1
#define DL_TPORTCHANNELTYP_R7_DCH 0
#define DL_TPORTCHANNELTYP_R7_FACH 1
#define DL_TPORTCHANNELTYP_R7_DSCH 2
#define DL_TPORTCHANNELTYP_R7_DCH_AND_DSCH 3
#define DL_TPORTCHANNELTYP_R7_HSDSCH 4
#define DL_TPORTCHANNELTYP_R7_DCH_AND_HSDSCH 5

#define DL_RLC_MODE_DL_AM_RLC_MODE 0
#define DL_RLC_MODE_DL_UM_RLC_MODE 1
#define DL_RLC_MODE_DL_TM_RLC_MODE 2

#define DL_RLC_MODE_R5_DL_AM_RLC_MODE 0
#define DL_RLC_MODE_R5_DL_UM_RLC_MODE 1
#define DL_RLC_MODE_R5_DL_TM_RLC_MODE 2

#define DL_RLC_MODE_R6_DL_AM_RLC_MODE 0
#define DL_RLC_MODE_R6_DL_UM_RLC_MODE 1
#define DL_RLC_MODE_R6_DL_TM_RLC_MODE 2

#define DL_RLC_MODE_R7_DL_AM_RLC_MODE 0
#define DL_RLC_MODE_R7_DL_UM_RLC_MODE 1
#define DL_RLC_MODE_R7_DL_TM_RLC_MODE 2

#define LOSSLESSSRNS_RELOCSUPPORT_SUPPORTED 0
#define LOSSLESSSRNS_RELOCSUPPORT_NOTSUPP 1

#define TRANSMISSIONRLC_DISCARD_TIMERBASEDEXPLICIT 0
#define TRANSMISSIONRLC_DISCARD_TIMERBASEDNOEXPLICIT 1
#define TRANSMISSIONRLC_DISCARD_MAXDAT_RETXS 2
#define TRANSMISSIONRLC_DISCARD_NODISCARD 3

#define UL_RLC_MODE_UL_AM_RLC_MODE 0
#define UL_RLC_MODE_UL_UM_RLC_MODE 1
#define UL_RLC_MODE_UL_TM_RLC_MODE 2
#define UL_RLC_MODE_SPARE 3

#define RLC_INFOCHOICE_RLC_INFO 0
#define RLC_INFOCHOICE_SAME_AS_RB 1

#define UL_TPORTCHANNELTYP_DCH 0
#define UL_TPORTCHANNELTYP_RACH 1
#define UL_TPORTCHANNELTYP_DUMMY 2
#define UL_TPORTCHANNELTYP_USCH 3

#define RLC_SIZELST_ALLSIZES 0
#define RLC_SIZELST_CONFIGURED 1
#define RLC_SIZELST_EXPLICITLST 2

#define UL_LOGCHANNELMAPPINGS_ONELOGCHANNEL 0
#define UL_LOGCHANNELMAPPINGS_TWOLOGCHANNELS 1

#define TFC_SUBSET_MINIMUMALLOWEDTFC_NUMBER 0
#define TFC_SUBSET_ALLOWEDTFC_LST 1
#define TFC_SUBSET_NON_ALLOWEDTFC_LST 2
#define TFC_SUBSET_RESTRICTEDTRCHINFOLST 3
#define TFC_SUBSET_FULLTFCS 4


#define GAINFACTORINFO_SIGNALLEDGAINFACTORS 0
#define GAINFACTORINFO_COMPUTEDGAINFACTORS 1

#define CTFCSIZE_CTFC2BIT 0
#define CTFCSIZE_CTFC4BIT 1
#define CTFCSIZE_CTFC6BIT 2
#define CTFCSIZE_CTFC8BIT 3
#define CTFCSIZE_CTFC12BIT 4
#define CTFCSIZE_CTFC16BIT 5
#define CTFCSIZE_CTFC24BIT 6

#define EXPLICITTFCS_CFG_COMPLETE 0
#define EXPLICITTFCS_CFG_ADDITION 1
#define EXPLICITTFCS_CFG_REMOVAL 2
#define EXPLICITTFCS_CFG_REPLACEMENT 3

#define TFCS_INFOFORDSCH_CTFC2BIT 0
#define TFCS_INFOFORDSCH_CTFC4BIT 1
#define TFCS_INFOFORDSCH_CTFC6BIT 2
#define TFCS_INFOFORDSCH_CTFC8BIT 3
#define TFCS_INFOFORDSCH_CTFC12BIT 4
#define TFCS_INFOFORDSCH_CTFC16BIT 5
#define TFCS_INFOFORDSCH_CTFC24BIT 6

#define TFCI_FIELD2_INFO_TFCI_RANGE 0
#define TFCI_FIELD2_INFO_EXPLICIT_CONFIG 1

#define TFCS_NORMALTFCI_SIGNALLING 0
#define TFCS_DUMMY 1


#define BITMODERLC_SIZEINFO_SIZETYP1 0
#define BITMODERLC_SIZEINFO_SIZETYP2 1
#define BITMODERLC_SIZEINFO_SIZETYP3 2
#define BITMODERLC_SIZEINFO_SIZETYP4 3

#define NUMBEROFTPORTBLOCKS_ZERO 0
#define NUMBEROFTPORTBLOCKS_ONE 1
#define NUMBEROFTPORTBLOCKS_SMALL 2
#define NUMBEROFTPORTBLOCKS_LARGE 3

#define LOGCHANNELLST_ALLSIZES 0
#define LOGCHANNELLST_CONFIGURED 1
#define LOGCHANNELLST_EXPLICITLST 2

#define RLC_SIZE_BITMODE 0
#define RLC_SIZE_OCTETMODETYP1 1

#define RLC_SIZE_BITMODE 0
#define RLC_SIZE_OCTETMODETYP1 1

#define CHANNELCODINGTYP_NOCODING 0
#define CHANNELCODINGTYP_CONVOLUTIONAL 1
#define CHANNELCODINGTYP_TURBO 2

#define TTI_TTI10 0
#define TTI_TTI20 1
#define TTI_TTI40 2
#define TTI_TTI80 3
#define TTI_DYNAMIC 4

#define OCTETMODERLC_SIZEINFOTYP2_SIZETYP1 0
#define OCTETMODERLC_SIZEINFOTYP2_SIZETYP2 1
#define OCTETMODERLC_SIZEINFOTYP2_SIZETYP3 2

#define COMMONTDD_CHOICE_BITMODERLC_SIZEINFO 0
#define COMMONTDD_CHOICE_OCTETMODERLC_SIZEINFOTYP1 1
#define RLC_SIZE_FDD 0
#define RLC_SIZE_TDD 1

#define COMMONTDD_CHOICE_BITMODERLC_SIZEINFO 0
#define COMMONTDD_CHOICE_OCTETMODERLC_SIZEINFOTYP1 1


#define TPORTFORMATSET_DEDICATEDTRANSCHTFS 0
#define TPORTFORMATSET_COMMONTRANSCHTFS 1

#define TFCS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFCS_SIGNALLINGMODE_SAMEASUL 1

#define DL_PARAMS_DL_DCH_TFCS 0
#define DL_PARAMS_SAMEASUL 1

#define TM_SIGNALLINGMODE_MODE1 0
#define TM_SIGNALLINGMODE_MODE2 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1

#define UL_DPCH_POWERCNTRLINFOPREDEF_FDD 0
#define UL_DPCH_POWERCNTRLINFOPREDEF_TDD 1

#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD1 0
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD2 1
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD4 2
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD8 3
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD16 4
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD32 5
#define REPETITIONPERIODANDLENGTH_REPETITIONPERIOD64 6


#define SF512_ANDPILOT_SFD4 0
#define SF512_ANDPILOT_SFD8 1
#define SF512_ANDPILOT_SFD16 2
#define SF512_ANDPILOT_SFD32 3
#define SF512_ANDPILOT_SFD64 4
#define SF512_ANDPILOT_SFD128 5
#define SF512_ANDPILOT_SFD256 6
#define SF512_ANDPILOT_SFD512 7



#define OTHER_NOTSTORED 0
#define OTHER_STOREDWITHDIFFERENTVALUETAG 1
#define PREDEFINEDCONFIGSTATUSINFO_STOREDWITHVALUETAGSAMEASPREVIUS 0
#define PREDEFINEDCONFIGSTATUSINFO_OTHER 1

#define RLC_INFOCHOICE_R5_RLC_INFO 0
#define RLC_INFOCHOICE_R5_SAME_AS_RB 1

#define RLC_INFOCHOICE_R6_RLC_INFO 0
#define RLC_INFOCHOICE_R6_SAME_AS_RB 1

#define RLC_SIZELST_ALLSIZES 0
#define RLC_SIZELST_CONFIGURED 1
#define RLC_SIZELST_EXPLICITLST 2
#define UL_TRCH_TYP_DCH_RACH_USCH 0
#define UL_TRCH_TYP_E_DCH 1

#define UL_LOGCHANNELMAPPINGS_R6_ONELOGCHANNEL 0
#define UL_LOGCHANNELMAPPINGS_R6_TWOLOGCHANNELS 1

#define RLC_INFOCHOICE_R7_RLC_INFO 0
#define RLC_INFOCHOICE_R7_SAME_AS_RB 1

#define RLC_SIZELST_ALLSIZES 0
#define RLC_SIZELST_CONFIGURED 1
#define RLC_SIZELST_EXPLICITLST 2
#define RLC_PDU_SIZE_FIXEDSIZE 0
#define RLC_PDU_SIZE_FLEXIBLESIZE 1
#define UL_TRCH_TYP_DCH_RACH_USCH 0
#define UL_TRCH_TYP_E_DCH 1

#define UL_LOGCHANNELMAPPINGS_R8_ONELOGCHANNEL 0
#define UL_LOGCHANNELMAPPINGS_R8_TWOLOGCHANNELS 1

#define RB_CHANGE_RELEASE 0
#define RB_CHANGE_RE_MAPTODEFAULTRB 1

#define TTI_TTI5 0
#define TTI_TTI10_1 1
#define TTI_TTI20_1 2
#define TTI_TTI40_1 3
#define TTI_TTI80_1 4
#define TTI_DYNAMIC_1 5

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1

#define DL_TRCH_TYPID1_R5_DCH 0
#define DL_TRCH_TYPID1_R5_DSCH 1
#define DL_TRCH_TYPID1_R5_HSDSCH 2

#define MEMORYPARTITIONING_IMPLICIT 0
#define MEMORYPARTITIONING_EXPLICIT 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1
#define TFS_SIGNALLINGMODE_HSDSCH 2

#define MEMORYPARTITIONING_IMPLICIT 0
#define MEMORYPARTITIONING_EXPLICIT 1

#define DL_MAC_HEADERTYP_MAC_HS 0
#define DL_MAC_HEADERTYP_MAC_EHS 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1
#define TFS_SIGNALLINGMODE_HSDSCH 2

#define DL_MAC_HEADERTYP_MAC_HS 0
#define DL_MAC_HEADERTYP_MAC_EHS 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1
#define TFS_SIGNALLINGMODE_HSDSCH 2

#define DL_MAC_HEADERTYP_MAC_HS 0
#define DL_MAC_HEADERTYP_MAC_EHS 1

#define TFS_SIGNALLINGMODE_EXPLICIT_CONFIG 0
#define TFS_SIGNALLINGMODE_SAMEASULTRCH 1
#define TFS_SIGNALLINGMODE_HSDSCH 2

#define DL_PARAMS_DL_DCH_TFCS 0
#define DL_PARAMS_SAMEASUL 1

#define DL_TRCH_TYPID2_R5_DCH 0
#define DL_TRCH_TYPID2_R5_DSCH 1
#define DL_TRCH_TYPID2_R5_HSDSCH 2

#define HSDSCH_MAC_HS 0
#define HSDSCH_MAC_EHS 1
#define DL_TRCH_TYPID2_R7_DCH 0
#define DL_TRCH_TYPID2_R7_DSCH 1
#define DL_TRCH_TYPID2_R7_HSDSCH 2

#define TRANSMISSIONGRANTTYP_NON_SCHEDULEDTRANSGRANTINFO 0
#define TRANSMISSIONGRANTTYP_SCHEDULEDTRANSMISSIONGRANTINFO 1

#define TRANSMISSIONGRANTTYP_NON_SCHEDULEDTRANSGRANTINFO 0
#define TRANSMISSIONGRANTTYP_SCHEDULEDTRANSMISSIONGRANTINFO 1



#define TPORTFORMATSET_LCR_DEDICATEDTRANSCHTFS 0
#define TPORTFORMATSET_LCR_COMMONTRANSCHTFS_LCR 1

#define UL_ADDRECONFTRANSCHINFO_R6_DCH_USCH 0
#define UL_ADDRECONFTRANSCHINFO_R6_E_DCH 1

#define MODESPECIFIC_FDD 0
#define MODESPECIFIC_TDD 1
#define UL_ADDRECONFTRANSCHINFO_R7_DCH_USCH 0
#define UL_ADDRECONFTRANSCHINFO_R7_E_DCH 1

#define MODESPECIFIC_FDD 0
#define MODESPECIFIC_TDD 1
#define UL_ADDRECONFTRANSCHINFO_R8_DCH_USCH 0
#define UL_ADDRECONFTRANSCHINFO_R8_E_DCH 1


#define UL_TPORTCHANNELIDENTITY_R6_DCH_USCH 0
#define UL_TPORTCHANNELIDENTITY_R6_E_DCH 1

#define SUBCHANNELSIZE_SIZE1 0
#define SUBCHANNELSIZE_SIZE2 1
#define SUBCHANNELSIZE_SIZE4 2
#define SUBCHANNELSIZE_SIZE8 3

#define SUBCHANNELSIZE_SIZE1 0
#define SUBCHANNELSIZE_SIZE2 1
#define SUBCHANNELSIZE_SIZE4 2
#define SUBCHANNELSIZE_SIZE8 3
#define SUBCHANNELSIZE_SIZE16 4

#define SUBCHANNELSIZE_SIZE1 0
#define SUBCHANNELSIZE_SIZE2 1
#define SUBCHANNELSIZE_SIZE4 2
#define SUBCHANNELSIZE_SIZE8 3

#define SECONDCPICH_PATTERN_NORMALPATTERN 0
#define SECONDCPICH_PATTERN_DIVERSITYPATTERN 1

#define SECONDARYCELLMIMOPARAMETERSFDD_R10_CONTINUE 0
#define SECONDARYCELLMIMOPARAMETERSFDD_R10_NEWCFG 1

#define CONFIGURATIONINFO_CONTINUE 0
#define CONFIGURATIONINFO_NEWCFG 1

#define UL_OL_PC_SIGNALLING_BROADCAST_UL_OL_PC_INFO 0
#define UL_OL_PC_SIGNALLING_INDIVIDUALLYSIGNALLED 1
#define UL_DPCH_POWERCNTRLINFO_FDD 0
#define UL_DPCH_POWERCNTRLINFO_TDD 1

#define UL_OL_PC_SIGNALLING_BROADCAST_UL_OL_PC_INFO 0
#define UL_OL_PC_SIGNALLING_INDIVIDUALLYSIGNALLED 1
#define UL_DPCH_POWERCNTRLINFO_R4_FDD 0
#define UL_DPCH_POWERCNTRLINFO_R4_TDD 1

#define UL_OL_PC_SIGNALLING_BROADCAST_UL_OL_PC_INFO 0
#define UL_OL_PC_SIGNALLING_INDIVIDUALLYSIGNALLED 1
#define UL_DPCH_POWERCNTRLINFO_R5_FDD 0
#define UL_DPCH_POWERCNTRLINFO_R5_TDD 1

#define TDDOPTION_TDD384 0
#define TDDOPTION_TDD768 1
#define TDDOPTION_TDD128 1
#define TDDOPTION_TDD128_2 2
#define UL_OL_PC_SIGNALLING_BROADCAST_UL_OL_PC_INFO 0
#define UL_OL_PC_SIGNALLING_INDIVIDUALLYSIGNALLED 1
#define UL_DPCH_POWERCNTRLINFO_R7_FDD 0
#define UL_DPCH_POWERCNTRLINFO_R7_TDD 1

#define CHANNELASSIGNMENTACTIVE_NOTACTIVE 0
#define CHANNELASSIGNMENTACTIVE_ISACTIVE 1

#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD1 0
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD2 1
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD4 2
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD8 3
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD16 4
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD32 5
#define REPETITIONPERIODLENGTHANDOFFSET_REPETITIONPERIOD64 6

#define E_AGCH_DRX_INFOTYP_SAMEASHS_SCCH 0
#define E_AGCH_DRX_INFOTYP_E_AGCH_DRX_PARAMS 1

#define CONTROLCHANNELDRXOPERATION_CONTINUE 0
#define CONTROLCHANNELDRXOPERATION_NEWOPERATION 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define MIDAMBLEALLOCNMODE_UESPECIFICMIDAMBLE 2
#define MIDAMBLEALLOCNMODE_UESPECIFICMIDAMBLE_1 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1
#define BURSTTYP_TYPE3 2

#define CODESREPRESENTATION_CONSECUTIVE 0
#define CODESREPRESENTATION_BITMAP 1

#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1

#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1


#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1
#define BURSTTYP_TYPE3 2
#define BURSTTYP_MBSFNBURSTTYP4 3

#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1
#define BURSTTYP_TYPE3 2
#define BURSTTYP_MBSFNBURSTTYP4 3

#define CODESREPRESENTATION_CONSECUTIVE 0
#define CODESREPRESENTATION_BITMAP 1

#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1


#define SF512_ANDCODENUMBER_SF4 0
#define SF512_ANDCODENUMBER_SF8 1
#define SF512_ANDCODENUMBER_SF16 2
#define SF512_ANDCODENUMBER_SF32 3
#define SF512_ANDCODENUMBER_SF64 4
#define SF512_ANDCODENUMBER_SF128 5
#define SF512_ANDCODENUMBER_SF256 6
#define SF512_ANDCODENUMBER_SF512 7


#define CFNHANDLING_MAINTAIN 0
#define CFNHANDLING_INITIALISE 1

#define UL_DL_MODE_UL 0
#define UL_DL_MODE_DL 1
#define UL_DL_MODE_UL_AND_DL 2

#define TGPS_STATUS_ACTIVATE 0
#define TGPS_STATUS_DEACTIVATE 1


#define CFNHANDLING_MAINTAIN 0
#define CFNHANDLING_INITIALISE 1


#define CFNHANDLING_MAINTAIN 0
#define CFNHANDLING_INITIALISE 1

#define CFNHANDLING_MAINTAIN 0
#define CFNHANDLING_INITIALISE 1

#define DL_DPCHINFOCMN_DL_DPCH_INFOCMN 0
#define DL_DPCHINFOCMN_DL_FDPCH_INFOCMN 1

#define DL_DPCHINFOCMN_DL_DPCH_INFOCMN 0
#define DL_DPCHINFOCMN_DL_FDPCH_INFOCMN 1

#define TGPS_STATUS_ACTIVATE 0
#define TGPS_STATUS_DEACTIVATE 1

#define DL_DPCHINFOCMN_DL_DPCH_INFOCMN 0
#define DL_DPCHINFOCMN_DL_FDPCH_INFOCMN 1

#define TGPS_STATUS_ACTIVATE 0
#define TGPS_STATUS_DEACTIVATE 1

#define DL_DPCHINFOCMN_DL_DPCH_INFOCMN 0
#define DL_DPCHINFOCMN_DL_FDPCH_INFOCMN 1

#define DL_DPCH_INFOPERRL_FDD 0
#define DL_DPCH_INFOPERRL_TDD 1

#define DL_DPCH_INFOPERRL_R4_FDD 0
#define DL_DPCH_INFOPERRL_R4_TDD 1

#define DL_DPCH_INFOPERRL_R5_FDD 0
#define DL_DPCH_INFOPERRL_R5_TDD 1

#define DL_DPCH_INFOPERRL_R6_FDD 0
#define DL_DPCH_INFOPERRL_R6_TDD 1

#define DL_DPCH_INFOPERRL_R7_FDD 0
#define DL_DPCH_INFOPERRL_R7_TDD 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1

#define SIGNALLINGMETHOD_CODERANGE 0
#define SIGNALLINGMETHOD_TFCI_RANGE 1
#define SIGNALLINGMETHOD_EXPLICIT_CONFIG 2
#define SIGNALLINGMETHOD_REPLACE 3

#define DL_SECONDARYCELLINFOFDD_CONTINUE 0
#define DL_SECONDARYCELLINFOFDD_NEWCFG 1

#define SECONDARYCELLMIMOPARAMETERSFDD_CONTINUE 0
#define SECONDARYCELLMIMOPARAMETERSFDD_NEWCFG 1

#define CONFIGURATIONINFO_CONTINUE 0
#define CONFIGURATIONINFO_NEWCFG 1

#define TGPS_STATUS_ACTIVATE 0
#define TGPS_STATUS_DEACTIVATE 1

#define TGPS_STATUS_ACTIVATE 0
#define TGPS_STATUS_DEACTIVATE 1

#define E_DCH_TTI_LENGTH_DTX_E_DCH_TTI_10MS 0
#define E_DCH_TTI_LENGTH_DTX_E_DCH_TTI_2MS 1

#define MIDAMBLEALLOCNMODE_DEFAULTMIDAMBLE 0
#define MIDAMBLEALLOCNMODE_COMMONMIDAMBLE 1
#define BURSTTYP_TYPE1 0
#define BURSTTYP_TYPE2 1

#define E_HICH_INFO_E_HICH_INFO 0
#define E_HICH_INFO_RELEASEINDICATOR 1
#define E_RGCH_INFO_E_RGCH_INFO 0
#define E_RGCH_INFO_RELEASEINDICATOR 1

#define E_RGCH_INFO_E_RGCH_INFO 0
#define E_RGCH_INFO_RELEASEINDICATOR 1

#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD1 0
#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD2 1
#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD4 2
#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD8 3
#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD16 4
#define REPETITIONPERIODANDLENGTHFORSPS_REPETITIONPERIOD32 5

#define MODESPECIFICINFO_TDD384 0
#define MODESPECIFICINFO_TDD768 1

#define TDD384_SF16 0
#define TDD384_SF8 1
#define TDD768_SF32 0
#define TDD768_SF816 1
#define MODESPECIFICINFO_TDD384_TDD768 0
#define MODESPECIFICINFO_TDD128 1


#define REPPERLENGTHOFFSET_PICH_RPP4_2 0
#define REPPERLENGTHOFFSET_PICH_RPP8_2 1
#define REPPERLENGTHOFFSET_PICH_RPP8_4 2
#define REPPERLENGTHOFFSET_PICH_RPP16_2 3
#define REPPERLENGTHOFFSET_PICH_RPP16_4 4
#define REPPERLENGTHOFFSET_PICH_RPP32_2 5
#define REPPERLENGTHOFFSET_PICH_RPP32_4 6
#define REPPERLENGTHOFFSET_PICH_RPP64_2 7
#define REPPERLENGTHOFFSET_PICH_RPP64_4 8

#define PICH_INFO_FDD 0
#define PICH_INFO_TDD 1

#define HS_SCCHLESSOPERATION_CONTINUE 0
#define HS_SCCHLESSOPERATION_NEWOPERATION 1


#define SECONDCPICH_PATTERN_NORMALPATTERN 0
#define SECONDCPICH_PATTERN_DIVERSITYPATTERN 1

#define TDD_TDD128 0
#define TDD_TDD384_TDD768 1

#define TDD_TDD128 0
#define TDD_TDD384_TDD768 1

#define MU_MIMO_INFO_TDD128_CONTINUE 0
#define MU_MIMO_INFO_TDD128_NEWCFG 1

#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1


#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1


#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1

#define PICH_FORHSDPASUPPPAG_TDD128_IMPLICIT 0
#define PICH_FORHSDPASUPPPAG_TDD128_EXPLICIT 1

#define CHANNELISATIONCODE_TDD384 0
#define CHANNELISATIONCODE_TDD768 1

#define PRACH_PARTITIONING_FDD 0
#define PRACH_PARTITIONING_TDD 1

#define PRACH_PARTITIONING_R7_FDD 0
#define PRACH_PARTITIONING_R7_TDD 1

#define TDD_PRACH_CCODELST_SF8 0
#define TDD_PRACH_CCODELST_SF16 1


#define TDD768_PRACH_CCODELST_SF32 0
#define TDD768_PRACH_CCODELST_SF16 1


#define SYNCCASE_SYNCCASE1 0
#define SYNCCASE_SYNCCASE2 1
#define PRIMARYCCPCH_INFO_FDD 0
#define PRIMARYCCPCH_INFO_TDD 1

#define SYNCCASE_SYNCCASE1 0
#define SYNCCASE_SYNCCASE2 1
#define TDDOPTION_TDD384_TDD768 0
#define PRIMARYCCPCH_INFO_R4_FDD 0
#define PRIMARYCCPCH_INFO_R4_TDD 1

#define SYNCCASE_SYNCCASE1 0
#define SYNCCASE_SYNCCASE2 1

#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1

#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1
#define PUSCH_ALLOCN_PUSCH_ALLOCNPENDING 0
#define PUSCH_ALLOCN_PUSCH_ALLOCNASSIGNMENT 1


#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1


#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1
#define PUSCH_ALLOCN_PUSCH_ALLOCNPENDING 0
#define PUSCH_ALLOCN_PUSCH_ALLOCNASSIGNMENT 1


#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1

#define CONFIGURATION_OLD_CFG 0
#define CONFIGURATION_NEW_CFG 1
#define PUSCH_ALLOCN_PUSCH_ALLOCNPENDING 0
#define PUSCH_ALLOCN_PUSCH_ALLOCNASSIGNMENT 1

#define REPPERLENGTHOFFSET_MICH_RPP4_2 0
#define REPPERLENGTHOFFSET_MICH_RPP8_2 1
#define REPPERLENGTHOFFSET_MICH_RPP8_4 2
#define REPPERLENGTHOFFSET_MICH_RPP16_2 3
#define REPPERLENGTHOFFSET_MICH_RPP16_4 4
#define REPPERLENGTHOFFSET_MICH_RPP32_2 5
#define REPPERLENGTHOFFSET_MICH_RPP32_4 6
#define REPPERLENGTHOFFSET_MICH_RPP64_2 7
#define REPPERLENGTHOFFSET_MICH_RPP64_4 8

#define SF256_ANDCODENUMBER_SF4 0
#define SF256_ANDCODENUMBER_SF8 1
#define SF256_ANDCODENUMBER_SF16 2
#define SF256_ANDCODENUMBER_SF32 3
#define SF256_ANDCODENUMBER_SF64 4
#define SF256_ANDCODENUMBER_SF128 5
#define SF256_ANDCODENUMBER_SF256 6



#define MODESPECIFICINFO_FDD 0
#define MODESPECIFICINFO_TDD384_1 1
#define MODESPECIFICINFO_TDD128_2 2

#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_32_OFFSET 0
#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_64_OFFSET 1
#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_128_OFFSET 2
#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_256_OFFSET 3
#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_512_OFFSET 4
#define MBMS_MSCHSCHEDULINGINFO_SCHEDULINGPERIOD_1024_OFFSET 5

#define MODULATION_MODQPSK 0
#define MODULATION_MOD16QAM 1
#define MODESPECIFICINFO_FDD 0
#define MODESPECIFICINFO_TDD768_2 2
#define MODESPECIFICINFO_TDD128_3 3


#define MODULATION_MODQPSK 0
#define MODULATION_MOD16QAM 1

#define TIMESLOTLST_R4_TDD384 0
#define TIMESLOTLST_R4_TDD128 1

#define TIMING_CONTINUE 0
#define TIMING_NEWTIMING 1


#define PARAMETERS_SAMEASLAST 0
#define PARAMETERS_NEWPARAMS 1

#define ADDITIONALTIMESLOTS_CONSECUTIVE 0
#define ADDITIONALTIMESLOTS_TIMESLOTLST 1
#define MORETIMESLOTS_NOMORE 0
#define MORETIMESLOTS_ADDITIONALTIMESLOTS 1


#define UL_TIMINGADVANCECNTRL_DISABLED 0
#define UL_TIMINGADVANCECNTRL_ENABLED 1


#define UL_CHANNELREQUIREMENT_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENT_DUMMY 1

#define UL_TIMINGADVANCECNTRL_R4_DISABLED 0
#define UL_TIMINGADVANCECNTRL_R4_ENABLED 1


#define UL_CHANNELREQUIREMENT_R4_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENT_R4_DUMMY 1


#define UL_CHANNELREQUIREMENT_R5_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENT_R5_DUMMY 1

#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_DUMMY1 1
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_DUMMY2 2

#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R4_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R4_DUMMY1 1
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R4_DUMMY2 2

#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R5_UL_DPCH_INFO 0
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R5_DUMMY1 1
#define UL_CHANNELREQUIREMENTWITHCPCH_SETID_R5_DUMMY2 2

#define CONFIGURATIONINFO_CONTINUE 0
#define CONFIGURATIONINFO_NEWCFG 1
#define UL_CLTD_INFOFDD_CONFIGURATIONINFO 0

#define UL_OL_PC_SIGNALLING_BROADCAST_UL_OL_PC_INFO 0
#define UL_OL_PC_SIGNALLING_INDIVIDUALLYSIGNALLED 1
#define UL_DPCH_POWERCNTRLINFO_R6_FDD 0
#define UL_DPCH_POWERCNTRLINFO_R6_TDD 1

#define DPDCHPRESENCE_PRESENT 0
#define DPDCHPRESENCE_NOTPRESENT 1

#define UL_TIMINGADVANCECNTRL_R7_DISABLED 0
#define UL_TIMINGADVANCECNTRL_R7_ENABLED 1

#define DPDCHPRESENCE_PRESENT 0
#define DPDCHPRESENCE_NOTPRESENT 1
#define MODESPECIFICINFO_FDD 0
#define MODESPECIFICINFO_TDD 1

#define UL_TIMINGADVANCECNTRL_LCR_R4_DISABLED 0
#define UL_TIMINGADVANCECNTRL_LCR_R4_ENABLED 1

#define BSICREPORTED_VERIFIEDBSIC 0
#define BSICREPORTED_NONVERIFIEDBSIC 1

#define FORBIDDENAFFECTCELL_FDD 0
#define FORBIDDENAFFECTCELL_TDD 1

#define INTRAFREQEVENT_E1A 0
#define INTRAFREQEVENT_E1B 1
#define INTRAFREQEVENT_E1C 2
#define INTRAFREQEVENT_E1D 3
#define INTRAFREQEVENT_E1E 4
#define INTRAFREQEVENT_E1F 5
#define INTRAFREQEVENT_E1G 6
#define INTRAFREQEVENT_E1H 7
#define INTRAFREQEVENT_E1I 8

#define RPRTNGCELLSTATUS_WITHINACTIVESET 0
#define RPRTNGCELLSTATUS_WITHINMONITOREDSETUSEDFREQ 1
#define RPRTNGCELLSTATUS_WITHINACTIVEANDORMONITOREDUSEDFREQ 2
#define RPRTNGCELLSTATUS_WITHINDETECTEDSETUSEDFREQ 3
#define RPRTNGCELLSTATUS_WITHINMONITOREDANDORDETECTEDUSEDFREQ 4
#define RPRTNGCELLSTATUS_ALLACTIVEPLUSMONITOREDSET 5
#define RPRTNGCELLSTATUS_ALLACTIVEPLUSDETECTEDSET 6
#define RPRTNGCELLSTATUS_ALLACTIVEPLUSMONITOREDANDORDETECTEDSET 7
#define RPRTNGCELLSTATUS_WITHINVIRTUALACTSET 8
#define RPRTNGCELLSTATUS_WITHINMONITOREDSETNONUSEDFREQ 9
#define RPRTNGCELLSTATUS_WITHINMONITOREDANDORVIRTUALACTIVESETNONUSEDFREQ 10
#define RPRTNGCELLSTATUS_ALLVIRTUALACTSETPLUSMONITOREDSETNONUSEDFREQ 11
#define RPRTNGCELLSTATUS_WITHINACTSETORVIRTUALACTSET_INTERRATCELLS 12
#define RPRTNGCELLSTATUS_WITHINACTSETANDORMONITOREDUSEDFREQORVIRTUALACTSETANDORMONITOREDNONUSEDFREQ 13

#define CELLDCH_REPORTCRITERIA_INTRAFREQRPRTNGCRITERIA 0
#define CELLDCH_REPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1

#define INTRAFREQEVENT_LCR_R4_E1A 0
#define INTRAFREQEVENT_LCR_R4_E1B 1
#define INTRAFREQEVENT_LCR_R4_E1C 2
#define INTRAFREQEVENT_LCR_R4_E1D 3
#define INTRAFREQEVENT_LCR_R4_E1E 4
#define INTRAFREQEVENT_LCR_R4_E1F 5
#define INTRAFREQEVENT_LCR_R4_E1G 6
#define INTRAFREQEVENT_LCR_R4_E1H 7
#define INTRAFREQEVENT_LCR_R4_E1I 8

#define CELLDCH_REPORTCRITERIA_LCR_R4_INTRAFREQRPRTNGCRITERIA 0
#define CELLDCH_REPORTCRITERIA_LCR_R4_PERIODICALRPRTNGCRITERIA 1

#define REFERENCETIMEDIFFERENCETOCELL_ACCURACY40 0
#define REFERENCETIMEDIFFERENCETOCELL_ACCURACY256 1
#define REFERENCETIMEDIFFERENCETOCELL_ACCURACY2560 2


#define TIMESLOTINFOLST_R4_TDD384 0
#define TIMESLOTINFOLST_R4_TDD128 1


#define PENALTYTIME_RSCP_NOTUSED 0
#define PENALTYTIME_RSCP_PT10 1
#define PENALTYTIME_RSCP_PT20 2
#define PENALTYTIME_RSCP_PT30 3
#define PENALTYTIME_RSCP_PT40 4
#define PENALTYTIME_RSCP_PT50 5
#define PENALTYTIME_RSCP_PT60 6

#define MODESPECIFICINFO_GSM 2


#define PENALTYTIME_ECN0_NOTUSED 0
#define PENALTYTIME_ECN0_PT10 1
#define PENALTYTIME_ECN0_PT20 2
#define PENALTYTIME_ECN0_PT30 3
#define PENALTYTIME_ECN0_PT40 4
#define PENALTYTIME_ECN0_PT50 5
#define PENALTYTIME_ECN0_PT60 6


#define SFN_SFN_OBSTIMEDIFFERENCE_TYPE1 0
#define SFN_SFN_OBSTIMEDIFFERENCE_TYPE2 1


#define CELLMEASUREMENTEVENTRESULTS_FDD 0
#define CELLMEASUREMENTEVENTRESULTS_TDD 1

#define CELLMEASUREMENTEVENTRESULTSONSECULFREQ_FDD 0
#define CELLMEASUREMENTEVENTRESULTSONSECULFREQ_SPARE 1


#define RADIOACCESSTECHNOLOGY_UTRA 0
#define RADIOACCESSTECHNOLOGY_E_UTRA 1

#define EUTRA_FREQUENCYREMOVAL_REMOVEALLFREQUENCIES 0
#define EUTRA_FREQUENCYREMOVAL_REMOVESOMEFREQUENCIES 1
#define EUTRA_FREQUENCYREMOVAL_REMOVENOFREQUENCIES 2

#define FORBIDDENAFFECTCELL_R4_FDD 0
#define FORBIDDENAFFECTCELL_R4_TDD 1

#define RPRTNGCELLSTATUS_R10_WITHINACTIVESET 0
#define RPRTNGCELLSTATUS_R10_WITHINMONITOREDSETUSEDFREQ 1
#define RPRTNGCELLSTATUS_R10_WITHINACTIVEANDORMONITOREDUSEDFREQ 2
#define RPRTNGCELLSTATUS_R10_WITHINDETECTEDSETUSEDFREQ 3
#define RPRTNGCELLSTATUS_R10_WITHINMONITOREDANDORDETECTEDUSEDFREQ 4
#define RPRTNGCELLSTATUS_R10_ALLACTIVEPLUSMONITOREDSET 5
#define RPRTNGCELLSTATUS_R10_ALLACTIVEPLUSDETECTEDSET 6
#define RPRTNGCELLSTATUS_R10_ALLACTIVEPLUSMONITOREDANDORDETECTEDSET 7
#define RPRTNGCELLSTATUS_R10_WITHINVIRTUALACTSET 8
#define RPRTNGCELLSTATUS_R10_WITHINMONITOREDSETNONUSEDFREQ 9
#define RPRTNGCELLSTATUS_R10_WITHINMONITOREDANDORVIRTUALACTIVESETNONUSEDFREQ 10
#define RPRTNGCELLSTATUS_R10_ALLVIRTUALACTSETPLUSMONITOREDSETNONUSEDFREQ 11
#define RPRTNGCELLSTATUS_R10_WITHINACTSETORVIRTUALACTSET_INTERRATCELLS 12
#define RPRTNGCELLSTATUS_R10_WITHINACTSETANDORMONITOREDUSEDFREQORVIRTUALACTSETANDORMONITOREDNONUSEDFREQ 13
#define RPRTNGCELLSTATUS_R10_ALLVIRTUALACTSETPLUSMONITOREDSETPLUSDETECTEDSETNONUSEDFREQ 14

#define UL_TRCH_IDENTITY_DCH 0
#define UL_TRCH_IDENTITY_RACHORCPCH 1
#define UL_TRCH_IDENTITY_USCH 2

#define UE_INTERNALEVENTRESULTS_EVENT6A 0
#define UE_INTERNALEVENTRESULTS_EVENT6B 1
#define UE_INTERNALEVENTRESULTS_EVENT6C 2
#define UE_INTERNALEVENTRESULTS_EVENT6D 3
#define UE_INTERNALEVENTRESULTS_EVENT6E 4
#define UE_INTERNALEVENTRESULTS_EVENT6F 5
#define UE_INTERNALEVENTRESULTS_EVENT6G 6
#define UE_INTERNALEVENTRESULTS_SPARE 7


#define POSITIONESTIMATE_ELLIPSOIDPOINT 0
#define POSITIONESTIMATE_ELLIPSOIDPOINTUNCERTCIRCLE 1
#define POSITIONESTIMATE_ELLIPSOIDPOINTUNCERTELLIPSE 2
#define POSITIONESTIMATE_ELLIPSOIDPOINTALTITUDE 3
#define POSITIONESTIMATE_ELLIPSOIDPOINTALTITUDEELLIPSE 4

#define REFERENCETIME_UTRAN_GPSREFERENCETIMERESULT 0
#define REFERENCETIME_GPS_REFERENCETIMEONLY 1
#define REFERENCETIME_CELL_TIMING 2



#define REFERENCETIME_UTRAN_GPSREFERENCETIMERESULT 0
#define REFERENCETIME_GPS_REFERENCETIMEONLY 1

#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_EVENT7A 0
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_EVENT7B 1
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_EVENT7C 2
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_ADDITIONALORREPLACEDPOSMEASEVENT 3

#define EVENTRESULTS_INTRAFREQEVENTRESULTS 0
#define EVENTRESULTS_INTERFREQEVENTRESULTS 1
#define EVENTRESULTS_INTERRATEVENTRESULTS 2
#define EVENTRESULTS_TRAFFICVOLUMEEVENTRESULTS 3
#define EVENTRESULTS_QUALITYEVENTRESULTS 4
#define EVENTRESULTS_UE_INTERNALEVENTRESULTS 5
#define EVENTRESULTS_UE_POSITIONING_MEASUREMENTEVENTRESULTS 6
#define EVENTRESULTS_SPARE 7

#define MODE_FDD 0
#define MODE_TDD 1

#define VELOCITYESTIMATE_HORIZONTALVELOCITY 0
#define VELOCITYESTIMATE_HORIZONTALWITHVERTICALVELOCITY 1
#define VELOCITYESTIMATE_HORIZONTALVELOCITYWITHUNCERTAINTY 2
#define VELOCITYESTIMATE_HORIZONTALWITHVERTICALVELOCITYANDUNCERTAINTY 3

#define REFERENCETIME_UTRAN_GANSSREFERENCETIMERESULT 0
#define REFERENCETIME_GANSSREFERENCETIMEONLY 1
#define REFERENCETIMEOPTIONS_EARLIER_THAN_R7 0
#define REFERENCETIMEOPTIONS_R7 1

#define REFERENCETIME_UTRAN_GANSSREFERENCETIMERESULT 0
#define REFERENCETIME_GANSSREFERENCETIMEONLY 1

#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_V770EXT_EVENT7A 0
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_V770EXT_EVENT7C 1
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_V770EXT_EVENT7D 2
#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_V770EXT_SPARE 3

#define EVENTRESULTS_V770EXT_UE_POSITIONING_MEASUREMENTEVENTRESULTS 0

#define UE_POSITIONING_MEASUREMENTEVENTRESULTS_V860EXT_EVENT7D 0

#define EVENTRESULTS_V860EXT_UE_POSITIONING_MEASUREMENTEVENTRESULTS 0

#define EVENTRESULTS_VA40EXT_INTERFREQEVENTRESULTS 0

#define UE_POSITIONING_GANSS_AUXILIARYINFO_GANSSID1 0
#define UE_POSITIONING_GANSS_AUXILIARYINFO_GANSSID3 1

#define REMOVEDINTERFREQCELLLST_REMOVEALLINTERFREQCELLS 0
#define REMOVEDINTERFREQCELLLST_REMOVESOMEINTERFREQCELLS 1
#define REMOVEDINTERFREQCELLLST_REMOVENOINTERFREQCELLS 2

#define MODESPECIFICINFO_NOINFO 0

#define MODESPECIFICINFO_NOINFO 0


#define MODESPECIFICINFO_NOINFO 0

#define INTERFREQEVENT_EVENT2A 0
#define INTERFREQEVENT_EVENT2B 1
#define INTERFREQEVENT_EVENT2C 2
#define INTERFREQEVENT_EVENT2D 3
#define INTERFREQEVENT_EVENT2E 4
#define INTERFREQEVENT_EVENT2F 5

#define INTERFREQEVENT_R6_EVENT2A 0
#define INTERFREQEVENT_R6_EVENT2B 1
#define INTERFREQEVENT_R6_EVENT2C 2
#define INTERFREQEVENT_R6_EVENT2D 3
#define INTERFREQEVENT_R6_EVENT2E 4
#define INTERFREQEVENT_R6_EVENT2F 5

#define INTERFREQEVENT_R10_EVENT2A 0
#define INTERFREQEVENT_R10_EVENT2B 1
#define INTERFREQEVENT_R10_EVENT2C 2
#define INTERFREQEVENT_R10_EVENT2D 3
#define INTERFREQEVENT_R10_EVENT2E 4
#define INTERFREQEVENT_R10_EVENT2F 5


#define REPORTINGCRITERIA_INTRAFREQRPRTNGCRITERIA 0
#define REPORTINGCRITERIA_INTERFREQRPRTNGCRITERIA 1

#define MODESPECIFICINFO_INTERFREQRACHRPRTNGTHRESHOLD 2
#define MODESPECIFICINFO_MAXREPORTEDCELLSONRACHINTERFREQ 3


#define INTERFREQREPORTCRITERIA_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_NORPRTNG 3

#define INTRAFREQEVENT_R4_E1A 0
#define INTRAFREQEVENT_R4_E1B 1
#define INTRAFREQEVENT_R4_E1C 2
#define INTRAFREQEVENT_R4_E1D 3
#define INTRAFREQEVENT_R4_E1E 4
#define INTRAFREQEVENT_R4_E1F 5
#define INTRAFREQEVENT_R4_E1G 6
#define INTRAFREQEVENT_R4_E1H 7
#define INTRAFREQEVENT_R4_E1I 8

#define INTERFREQREPORTCRITERIA_R4_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_R4_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_R4_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_R4_NORPRTNG 3

#define INTRAFREQEVENT_R6_E1A 0
#define INTRAFREQEVENT_R6_E1B 1
#define INTRAFREQEVENT_R6_E1C 2
#define INTRAFREQEVENT_R6_E1D 3
#define INTRAFREQEVENT_R6_E1E 4
#define INTRAFREQEVENT_R6_E1F 5
#define INTRAFREQEVENT_R6_E1G 6
#define INTRAFREQEVENT_R6_E1H 7
#define INTRAFREQEVENT_R6_E1I 8
#define INTRAFREQEVENT_R6_E1J 9

#define INTERFREQREPORTCRITERIA_R6_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_R6_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_R6_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_R6_NORPRTNG 3

#define INTRAFREQEVENT_R7_E1A 0
#define INTRAFREQEVENT_R7_E1B 1
#define INTRAFREQEVENT_R7_E1C 2
#define INTRAFREQEVENT_R7_E1D 3
#define INTRAFREQEVENT_R7_E1E 4
#define INTRAFREQEVENT_R7_E1F 5
#define INTRAFREQEVENT_R7_E1G 6
#define INTRAFREQEVENT_R7_E1H 7
#define INTRAFREQEVENT_R7_E1I 8
#define INTRAFREQEVENT_R7_E1J 9

#define INTERFREQREPORTCRITERIA_R7_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_R7_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_R7_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_R7_NORPRTNG 3

#define INTRAFREQEVENTONSECULFREQ_E1A 0
#define INTRAFREQEVENTONSECULFREQ_E1B 1
#define INTRAFREQEVENTONSECULFREQ_E1C 2
#define INTRAFREQEVENTONSECULFREQ_E1E 3
#define INTRAFREQEVENTONSECULFREQ_E1F 4

#define INTERFREQREPORTCRITERIA_R9_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_R9_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_R9_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_R9_NORPRTNG 3

#define INTERFREQREPORTCRITERIA_R10_INTRAFREQRPRTNGCRITERIA 0
#define INTERFREQREPORTCRITERIA_R10_INTERFREQRPRTNGCRITERIA 1
#define INTERFREQREPORTCRITERIA_R10_PERIODICALRPRTNGCRITERIA 2
#define INTERFREQREPORTCRITERIA_R10_NORPRTNG 3

#define UE_AUTONOMOUSUPDMODE_DUMMY 0
#define UE_AUTONOMOUSUPDMODE_ONWITHNORPRTNG 1
#define UE_AUTONOMOUSUPDMODE_DUMMY2 2

#define TECHNOLOGYSPECIFICINFO_GSM 0
#define TECHNOLOGYSPECIFICINFO_IS_2000 1
#define TECHNOLOGYSPECIFICINFO_SPARE2 2
#define TECHNOLOGYSPECIFICINFO_SPARE1 3

#define REMOVEDINTERRATCELLLST_REMOVEALLINTERRATCELLS 0
#define REMOVEDINTERRATCELLLST_REMOVESOMEINTERRATCELLS 1
#define REMOVEDINTERRATCELLLST_REMOVENOINTERRATCELLS 2

#define TECHNOLOGYSPECIFICINFO_GSM 0
#define TECHNOLOGYSPECIFICINFO_IS_2000 1
#define TECHNOLOGYSPECIFICINFO_ABSENT 2
#define TECHNOLOGYSPECIFICINFO_SPARE1 3

#define TECHNOLOGYSPECIFICINFO_GSM 0
#define TECHNOLOGYSPECIFICINFO_IS_2000 1
#define TECHNOLOGYSPECIFICINFO_ABSENT 2
#define TECHNOLOGYSPECIFICINFO_SPARE1 3

#define INTERRATEVENT_EVENT3A 0
#define INTERRATEVENT_EVENT3B 1
#define INTERRATEVENT_EVENT3C 2
#define INTERRATEVENT_EVENT3D 3

#define RATSPECIFICINFO_GSM 0
#define RATSPECIFICINFO_IS_2000 1

#define RATSPECIFICINFO_GSM 0
#define RATSPECIFICINFO_IS_2000 1
#define RATSPECIFICINFO_E_UTRA 2

#define INTERRATMEASUREDRESULTS_GSM 0
#define INTERRATMEASUREDRESULTS_SPARE 1

#define RATSPECIFICINFO_GSM 0

#define INTERRATREPORTCRITERIA_INTERRATRPRTNGCRITERIA 0
#define INTERRATREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define INTERRATREPORTCRITERIA_NORPRTNG 2

#define RATSPECIFICINFO_GSM 0
#define RATSPECIFICINFO_EUTRA 1

#define INTERRATMEASUREMENTOBJECTS_INTERRATCELLINFOLST 0
#define INTERRATMEASUREMENTOBJECTS_EUTRA_FREQUENCYLST 1

#define INTERRATMEASUREMENTOBJECTS_INTERRATCELLINFOLST 0
#define INTERRATMEASUREMENTOBJECTS_EUTRA_FREQUENCYLST 1

#define REMOVEDINTRAFREQCELLLST_REMOVEALLINTRAFREQCELLS 0
#define REMOVEDINTRAFREQCELLLST_REMOVESOMEINTRAFREQCELLS 1
#define REMOVEDINTRAFREQCELLLST_REMOVENOINTRAFREQCELLS 2

#define REMOVEDINTRAFREQCELLLSTONSECULFREQ_REMOVEALLINTRAFREQCELLS 0
#define REMOVEDINTRAFREQCELLLSTONSECULFREQ_REMOVESOMEINTRAFREQCELLS 1
#define REMOVEDINTRAFREQCELLLSTONSECULFREQ_REMOVENOINTRAFREQCELLS 2


#define MODESPECIFICINFO_NOINFO 0


#define INTRAFREQREPORTCRITERIA_INTRAFREQRPRTNGCRITERIA 0
#define INTRAFREQREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define INTRAFREQREPORTCRITERIA_NORPRTNG 2

#define INTRAFREQREPORTCRITERIA_R4_INTRAFREQRPRTNGCRITERIA 0
#define INTRAFREQREPORTCRITERIA_R4_PERIODICALRPRTNGCRITERIA 1
#define INTRAFREQREPORTCRITERIA_R4_NORPRTNG 2

#define INTRAFREQREPORTCRITERIA_R6_INTRAFREQRPRTNGCRITERIA 0
#define INTRAFREQREPORTCRITERIA_R6_PERIODICALRPRTNGCRITERIA 1
#define INTRAFREQREPORTCRITERIA_R6_NORPRTNG 2

#define INTRAFREQREPORTCRITERIA_R7_INTRAFREQRPRTNGCRITERIA 0
#define INTRAFREQREPORTCRITERIA_R7_PERIODICALRPRTNGCRITERIA 1
#define INTRAFREQREPORTCRITERIA_R7_NORPRTNG 2

#define INTRAFREQREPORTCRITERIA_R9_INTRAFREQRPRTNGCRITERIA 0
#define INTRAFREQREPORTCRITERIA_R9_PERIODICALRPRTNGCRITERIA 1
#define INTRAFREQREPORTCRITERIA_R9_NORPRTNG 2

#define LOGGINGABSOLUTETHRESHOLD_RSCPFORANR 0
#define LOGGINGABSOLUTETHRESHOLD_EC_N0FORANR 1

#define LOGGEDCELLINFO_LOGGEDUTRACELLINFO 0
#define LOGGEDCELLINFO_LOGGEDEUTRACELLINFO 1
#define LOGGEDCELLINFO_LOGGEDGSMCELLINFO 2

#define AREACFG_CELLIDLST 0
#define AREACFG_LOCATIONAREALST 1
#define AREACFG_ROUTINGAREALST 2

#define LOGGEDMEASLOCINFO_ELLIPSOIDPOINT 0
#define LOGGEDMEASLOCINFO_ELLIPSOIDPOINTALTITUDE 1




#define MEASUREDRESULTS_INTRAFREQMEASUREDRESULTSLST 0
#define MEASUREDRESULTS_INTERFREQMEASUREDRESULTSLST 1
#define MEASUREDRESULTS_INTERRATMEASUREDRESULTSLST 2
#define MEASUREDRESULTS_TRAFFICVOLUMEMEASUREDRESULTSLST 3
#define MEASUREDRESULTS_QUALITYMEASUREDRESULTS 4
#define MEASUREDRESULTS_UE_INTERNALMEASUREDRESULTS 5
#define MEASUREDRESULTS_UE_POSITIONING_MEASUREDRESULTS 6
#define MEASUREDRESULTS_SPARE 7


#define MEASUREDRESULTS_V590EXT_INTRAFREQUENCYMEASUREDRESULTSLST 0
#define MEASUREDRESULTS_V590EXT_INTERFREQUENCYMEASUREDRESULTSLST 1

#define MODESPECIFICINFO_TDD384_768 0
#define MODESPECIFICINFO_TDD128 1

#define MEASUREDRESULTS_V770EXT_UEINTERNALMEASUREDRESULTS 0
#define MEASUREDRESULTS_V770EXT_UE_POSITIONING_MEASUREDRESULTS 1

#define MEASUREDRESULTS_V860EXT_UE_POSITIONING_MEASUREDRESULTS 0

#define MEASUREDRESULTS_V920EXT_INTRAFREQMEASUREDRESULTSLST 0
#define MEASUREDRESULTS_V920EXT_INTERFREQMEASUREDRESULTSLST 1

#define MEASUREDRESULTS_LCR_R4_INTRAFREQMEASUREDRESULTSLST 0
#define MEASUREDRESULTS_LCR_R4_INTERFREQMEASUREDRESULTSLST 1
#define MEASUREDRESULTS_LCR_R4_INTERRATMEASUREDRESULTSLST 2
#define MEASUREDRESULTS_LCR_R4_TRAFFICVOLUMEMEASUREDRESULTSLST 3
#define MEASUREDRESULTS_LCR_R4_QUALITYMEASUREDRESULTS 4
#define MEASUREDRESULTS_LCR_R4_UE_INTERNALMEASUREDRESULTS 5
#define MEASUREDRESULTS_LCR_R4_UE_POSITIONIING_MEASUREDRESULTS 6
#define MEASUREDRESULTS_LCR_R4_SPARE 7

#define MEASUREMENTQUANTITY_CPICH_EC_N0 0
#define MEASUREMENTQUANTITY_CPICH_RSCP 1
#define MEASUREMENTQUANTITY_PATHLOSS 2
#define MEASUREMENTQUANTITY_SPARE 3

#define MEASUREMENTQUANTITY_CPICH_EC_N0 0
#define MEASUREMENTQUANTITY_CPICH_RSCP 1
#define MEASUREMENTQUANTITY_PATHLOSS 2
#define MEASUREMENTQUANTITY_SPARE 3

#define UE_POSITIONING_EVENTSPECIFICINFO_E7A 0
#define UE_POSITIONING_EVENTSPECIFICINFO_E7B 1
#define UE_POSITIONING_EVENTSPECIFICINFO_E7C 2

#define UE_POSITIONING_REPORTCRITERIA_UE_POSITIONING_RPRTNGCRITERIA 0
#define UE_POSITIONING_REPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define UE_POSITIONING_REPORTCRITERIA_NORPRTNG 2

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1


#define TRAFFICVOLUMEMEASQUANTITY_RLC_BUFFERPAYLOAD 0
#define TRAFFICVOLUMEMEASQUANTITY_AVERAGERLC_BUFFERPAYLOAD 1
#define TRAFFICVOLUMEMEASQUANTITY_VARIANCEOFRLC_BUFFERPAYLOAD 2

#define TRAFFICVOLUMEREPORTCRITERIA_TRAFFICVOLUMERPRTNGCRITERIA 0
#define TRAFFICVOLUMEREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define TRAFFICVOLUMEREPORTCRITERIA_NORPRTNG 2


#define QUALITYREPORTCRITERIA_QUALITYRPRTNGCRITERIA 0
#define QUALITYREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define QUALITYREPORTCRITERIA_NORPRTNG 2


#define UE_INTERNALEVENTPARAM_EVENT6A 0
#define UE_INTERNALEVENTPARAM_EVENT6B 1
#define UE_INTERNALEVENTPARAM_EVENT6C 2
#define UE_INTERNALEVENTPARAM_EVENT6D 3
#define UE_INTERNALEVENTPARAM_EVENT6E 4
#define UE_INTERNALEVENTPARAM_EVENT6F 5
#define UE_INTERNALEVENTPARAM_EVENT6G 6

#define UE_INTERNALREPORTCRITERIA_UE_INTERNALRPRTNGCRITERIA 0
#define UE_INTERNALREPORTCRITERIA_PERIODICALRPRTNGCRITERIA 1
#define UE_INTERNALREPORTCRITERIA_NORPRTNG 2

#define MEASUREMENTTYP_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_UE_POSITIONING_MEASUREMENT 3
#define MEASUREMENTTYP_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_UE_INTERNALMEASUREMENT 6

#define MEASUREMENTCMD_SETUP 0
#define MEASUREMENTCMD_MODIFY 1
#define MEASUREMENTCMD_RELEASE 2

#define REFERENCECELLPOSITION_ELLIPSOIDPOINT 0
#define REFERENCECELLPOSITION_ELLIPSOIDPOINTWITHALTITUDE 1

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1


#define MEASUREMENTTYP_R4_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R4_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R4_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R4_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R4_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R4_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R4_UE_INTERNALMEASUREMENT 6

#define MEASUREMENTCMD_R4_SETUP 0
#define MEASUREMENTCMD_R4_MODIFY 1
#define MEASUREMENTCMD_R4_RELEASE 2

#define MEASUREMENTTYP_R6_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R6_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R6_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R6_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R6_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R6_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R6_UE_INTERNALMEASUREMENT 6

#define MEASUREMENTCMD_R6_SETUP 0
#define MEASUREMENTCMD_R6_MODIFY 1
#define MEASUREMENTCMD_R6_RELEASE 2

#define UE_POSITIONING_EVENTSPECIFICINFO_R7_E7A 0
#define UE_POSITIONING_EVENTSPECIFICINFO_R7_E7B 1
#define UE_POSITIONING_EVENTSPECIFICINFO_R7_E7C 2
#define UE_POSITIONING_EVENTSPECIFICINFO_R7_E7D 3

#define UE_POSITIONING_REPORTCRITERIA_R7_UE_POSITIONING_RPRTNGCRITERIA 0
#define UE_POSITIONING_REPORTCRITERIA_R7_PERIODICALRPRTNGCRITERIA 1
#define UE_POSITIONING_REPORTCRITERIA_R7_NORPRTNG 2

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1

#define POSITIONINGMODE_UEBASED 0
#define POSITIONINGMODE_UEASSISTED 1

#define MODE_FDD 0
#define MODE_TDD 1

#define MEASUREMENTTYP_R7_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R7_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R7_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R7_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R7_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R7_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R7_UE_INTERNALMEASUREMENT 6

#define MEASUREMENTCMD_R7_SETUP 0
#define MEASUREMENTCMD_R7_MODIFY 1
#define MEASUREMENTCMD_R7_RELEASE 2

#define MEASUREMENTTYP_R8_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R8_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R8_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R8_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R8_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R8_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R8_UE_INTERNALMEASUREMENT 6

#define MEASUREMENTCMD_R8_SETUP 0
#define MEASUREMENTCMD_R8_MODIFY 1
#define MEASUREMENTCMD_R8_RELEASE 2

#define MEASUREMENTTYP_R9_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R9_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R9_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R9_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R9_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R9_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R9_UE_INTERNALMEASUREMENT 6
#define MEASUREMENTTYP_R9_CSGPROXIMITYDETECTION 7

#define MEASUREMENTCMD_R9_SETUP 0
#define MEASUREMENTCMD_R9_MODIFY 1
#define MEASUREMENTCMD_R9_RELEASE 2

#define MODE_FDD 0
#define MODE_TDD 1

#define MEASUREMENTTYP_R10_INTRAFREQUENCYMEASUREMENT 0
#define MEASUREMENTTYP_R10_INTERFREQUENCYMEASUREMENT 1
#define MEASUREMENTTYP_R10_INTERRATMEASUREMENT 2
#define MEASUREMENTTYP_R10_UP_MEASUREMENT 3
#define MEASUREMENTTYP_R10_TRAFFICVOLUMEMEASUREMENT 4
#define MEASUREMENTTYP_R10_QUALITYMEASUREMENT 5
#define MEASUREMENTTYP_R10_UE_INTERNALMEASUREMENT 6
#define MEASUREMENTTYP_R10_CSGPROXIMITYDETECTION 7

#define MEASUREMENTCMD_R10_SETUP 0
#define MEASUREMENTCMD_R10_MODIFY 1
#define MEASUREMENTCMD_R10_RELEASE 2

#define TRAFFICVOLUMEREPORTCRITERIASYSINFO_TRAFFICVOLUMERPRTNGCRITERIA 0
#define TRAFFICVOLUMEREPORTCRITERIASYSINFO_PERIODICALRPRTNGCRITERIA 1

#define CELLSELECTQUALITYMEASURE_CPICH_RSCP 0
#define CELLSELECTQUALITYMEASURE_CPICH_EC_N0 1
#define USE_OF_HCS_HCS_NOT_USED 0
#define USE_OF_HCS_HCS_USED 1

#define CELLSELECTQUALITYMEASURE_CPICH_EC_N0 1
#define USE_OF_HCS_HCS_NOT_USED 0
#define USE_OF_HCS_HCS_USED 1

#define CELLSELECTQUALITYMEASURE_CPICH_EC_N0 1
#define USE_OF_HCS_HCS_NOT_USED 0
#define USE_OF_HCS_HCS_USED 1

#define CELLSELECTQUALITYMEASURE_CPICH_EC_N0 1
#define USE_OF_HCS_HCS_NOT_USED 0
#define USE_OF_HCS_HCS_USED 1


#define INTERRAT_CHANGEFAILCAUSE_CONFIGURATIONUNACCEPTABLE 0
#define INTERRAT_CHANGEFAILCAUSE_PHYSICALCHANNELFAIL 1
#define INTERRAT_CHANGEFAILCAUSE_PROTOCOLERR 2
#define INTERRAT_CHANGEFAILCAUSE_UNSPECIFIED 3
#define INTERRAT_CHANGEFAILCAUSE_SPARE4 4
#define INTERRAT_CHANGEFAILCAUSE_SPARE3 5
#define INTERRAT_CHANGEFAILCAUSE_SPARE2 6
#define INTERRAT_CHANGEFAILCAUSE_SPARE1 7

#define INTERRAT_UE_RADIOACCESSCAP_GSM 0
#define INTERRAT_UE_RADIOACCESSCAP_CDMA2000 1

#define INTERRAT_UE_SECCAP_GSM 0

#define INTERRAT_HO_FAILCAUSE_CONFIGURATIONUNACCEPTABLE 0
#define INTERRAT_HO_FAILCAUSE_PHYSICALCHANNELFAIL 1
#define INTERRAT_HO_FAILCAUSE_PROTOCOLERR 2
#define INTERRAT_HO_FAILCAUSE_INTERRAT_PROTERR 3
#define INTERRAT_HO_FAILCAUSE_UNSPECIFIED 4
#define INTERRAT_HO_FAILCAUSE_SPARE11 5
#define INTERRAT_HO_FAILCAUSE_SPARE10 6
#define INTERRAT_HO_FAILCAUSE_SPARE9 7
#define INTERRAT_HO_FAILCAUSE_SPARE8 8
#define INTERRAT_HO_FAILCAUSE_SPARE7 9
#define INTERRAT_HO_FAILCAUSE_SPARE6 10
#define INTERRAT_HO_FAILCAUSE_SPARE5 11
#define INTERRAT_HO_FAILCAUSE_SPARE4 12
#define INTERRAT_HO_FAILCAUSE_SPARE3 13
#define INTERRAT_HO_FAILCAUSE_SPARE2 14
#define INTERRAT_HO_FAILCAUSE_SPARE1 15

#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_32 0
#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_64 1
#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_128 2
#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_256 3
#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_512 4
#define MBMS_L1COMBININGSCHEDULE_CYCLELENGTH_1024 5

#define MBMS_L23CFG_SAMEASCURRENT 0
#define MBMS_L23CFG_DIFFERENT 1

#define MODE_FDD 0
#define MODE_TDD384_1 1
#define MODE_TDD128 2

#define MODE_TDD384 0
#define MODE_TDD768 1

#define MODE_IMB384 0

#define OTHER_SAMEASMIB_MULTIPLMN_ID 0
#define OTHER_EXPLICITPLMN_ID 1
#define PLMN_IDENTITY_SAMEASMIB_PLMN_ID 0
#define PLMN_IDENTITY_OTHER 1

#define MBMS_PREFERREDFREQUENCY_MCCH 0
#define MBMS_PREFERREDFREQUENCY_DCCH 1

#define LAYER1COMBINING_FDD 0
#define LAYER1COMBINING_TDD 1

#define LAYER1COMBINING_FDD 0
#define LAYER1COMBINING_TDD 1

#define LAYERCONVERGENCEINFO_MBMS_QOFFSET 0
#define LAYERCONVERGENCEINFO_MBMS_HCSOFFSET 1

#define STATUS_NONE 0
#define STATUS_SOME 1

#define MBSFNSERVICESNOTIFICATION_MBSFNSERVICESNOTIFIED 0
#define MBSFNSERVICESNOTIFICATION_MBSFNSERVICESNOTNOTIFIED 1

#define PREDEFINEDCONFIGSTATUSLST_ABSENT 0
#define PREDEFINEDCONFIGSTATUSLST_PRESENT 1
#define UE_SECINFO_ABSENT 0
#define UE_SECINFO_PRESENT 1
#define UE_CAPCONT_ABSENT 0
#define UE_CAPCONT_PRESENT 1
#define V390NONCRITICALEXTNS_ABSENT 0
#define V390NONCRITICALEXTNS_PRESENT 1

#define INTERRATHOVRINFOWITHINTERRATCAPABILITIES_R3_R3 0
#define INTERRATHOVRINFOWITHINTERRATCAPABILITIES_R3_CRITICALEXTNS 1

#define MEASUREMENTCMDWITHTYP_SETUP 0
#define MEASUREMENTCMDWITHTYP_MODIFY 1
#define MEASUREMENTCMDWITHTYP_RELEASE 2


#define CURRENT_TGPS_STATUS_ACTIVE 0
#define CURRENT_TGPS_STATUS_INACTIVE 1

#define SUPPORTFORRFC2507_NOTSUPP 0
#define SUPPORTFORRFC2507_SUPPORTED 1
#define SUPPORTFORRFC3095_NOTSUPP 0
#define SUPPORTFORRFC3095_SUPPORTED 1

#define MEASUREMENTCMDWITHTYP_R4_SETUP 0
#define MEASUREMENTCMDWITHTYP_R4_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R4_RELEASE 2

#define DUMMY_FDD 0
#define DUMMY_TDD 1

#define SUPPORTFORRFC2507_NOTSUPP 0
#define SUPPORTFORRFC2507_SUPPORTED 1
#define SUPPORTFORRFC3095_NOTSUPP 0
#define SUPPORTFORRFC3095_SUPPORTED 1

#define FDD_HSPDSCH_SUPPORTED 0
#define FDD_HSPDSCH_UNSUPPORTED 1

#define TDD384_HSPDSCH_SUPPORTED 0
#define TDD384_HSPDSCH_UNSUPPORTED 1

#define TDD128_HSPDSCH_SUPPORTED 0
#define TDD128_HSPDSCH_UNSUPPORTED 1

#define MEASUREMENTCMD_V590EXT_INTRA_FREQUENCY 0
#define MEASUREMENTCMD_V590EXT_INTER_FREQUENCY 1

#define DUMMY_FDD 0
#define DUMMY_TDD 1

#define SUPPORTFORRFC2507_NOTSUPP 0
#define SUPPORTFORRFC2507_SUPPORTED 1
#define SUPPORTFORRFC3095_NOTSUPP 0
#define SUPPORTFORRFC3095_SUPPORTED 1

#define MEASUREMENTCMDWITHTYP_R6_SETUP 0
#define MEASUREMENTCMDWITHTYP_R6_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R6_RELEASE 2

#define MEASUREMENTCMDWITHTYP_R7_SETUP 0
#define MEASUREMENTCMDWITHTYP_R7_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R7_RELEASE 2

#define MEASUREMENTCMDWITHTYP_R8_SETUP 0
#define MEASUREMENTCMDWITHTYP_R8_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R8_RELEASE 2

#define CURRENT_TGPS_STATUS_ACTIVE 0
#define CURRENT_TGPS_STATUS_INACTIVE 1

#define MEASUREMENTCMDWITHTYP_R9_SETUP 0
#define MEASUREMENTCMDWITHTYP_R9_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R9_RELEASE 2

#define MEASUREMENTCMDWITHTYP_R10_SETUP 0
#define MEASUREMENTCMDWITHTYP_R10_MODIFY 1
#define MEASUREMENTCMDWITHTYP_R10_RELEASE 2

#define CRITICALEXTNS_R11 0
#define CRITICALEXTNS_CRITICALEXTNS 1
#define CRITICALEXTNS_R10 0
#define CRITICALEXTNS_R9 0
#define CRITICALEXTNS_R8 0
#define CRITICALEXTNS_R7 0
#define CRITICALEXTNS_R6 0
#define CRITICALEXTNS_R5 0
#define LATER_THAN_R3_R4 0
#define LATER_THAN_R3_CRITICALEXTNS 1
#define SRNC_RELOCATIONINFO_R3_R3 0
#define SRNC_RELOCATIONINFO_R3_LATER_THAN_R3 1

#define RFC3095_CTXTINFO_R5_R5 0
#define RFC3095_CTXTINFO_R5_CRITICALEXTNS 1

#define TOTGTRNC_CONT_INTERRATHOVRINFO 0
#define TOTGTRNC_CONT_SRNCRELOCATION 1
#define TOTGTRNC_CONT_RFC3095_CTXTINFO 2
#define TOTGTRNC_CONT_EXTENSION 3

#endif
/**********************************************************************
         End of file:     nhu_3gasn.h@@/main/1 - Fri Dec 11 18:45:13 2009
**********************************************************************/
/**********************************************************************

        Revision history:

**********************************************************************/
/********************************************************************90**

     ver       pat    init                  description
------------ -------- ---- ----------------------------------------------
/main/1      ---    ch        1. RRC LTE Initial Release.
*********************************************************************91*/

